//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterBacalar_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int answer_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string answer_text { get; set; }
        public Nullable<bool> is_correct { get; set; }
        public Nullable<int> answer_score { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
