//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterBacalar_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTable
    {
        public int log_id { get; set; }
        public Nullable<int> user_id_ { get; set; }
        public Nullable<int> rezult_id { get; set; }
        public Nullable<int> test_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> answer_id { get; set; }
        public Nullable<bool> is_correct { get; set; }
        public Nullable<int> score { get; set; }
    }
}
