//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterBacalar_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTable
    {
        public int log_id { get; set; }
        public Nullable<int> user_id_ { get; set; }
        public Nullable<int> rezult_id { get; set; }
        public Nullable<int> test_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> answer_id { get; set; }
        public Nullable<bool> is_correct { get; set; }
        public Nullable<int> score { get; set; }
    }
}
