//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterBacalar_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezult
    {
        public int rezult_id { get; set; }
        public Nullable<int> user_id_ { get; set; }
        public Nullable<int> test_id { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> total_score { get; set; }
        public Nullable<System.DateTime> data_time { get; set; }
    
        public virtual Tests Tests { get; set; }
        public virtual Users Users { get; set; }
    }
}
